kind: Deployment
apiVersion: apps/v1
metadata:
  name: user
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 5467438/cloud_user:tagVersion
        ports:
        - containerPort: 8080
